import type { Metadata } from "next";
import "./globals.css";
import { Cuprum } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster";
import { Navbar } from "@/components/navbar/Navbar";

const inter = Cuprum({
  subsets: ['cyrillic'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={inter.className}>
      <body 
      >
        <Navbar />
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
